### PR TITLE
build: enable parallel Docker builds for multiple platforms

### PR DESCRIPTION
**Pull request by balaji-sivasakthi**
## Proposed Changes

Enable parallel Docker builds for multiple platforms

### Associated Issue

#1803 

### Architecture changes

- Remove this section if not used

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Review by sainak — CHANGES_REQUESTED** [review]
https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

**Comment by balaji-sivasakthi** [comment]
@sainak How do I check my forked repository? Does it require any settings?

**Comment by balaji-sivasakthi** [comment]
@sainak Is this expected? https://github.com/balaji-sivasakthi/care/actions/runs/8158452073/job/22300432336

**Comment by balaji-sivasakthi** [comment]
@sainak https://github.com/balaji-sivasakthi/care/actions/runs/8160557773

**Pull request closed without merging**
