### PR TITLE
Move tests from pytest to django unnittest

### PR DESCRIPTION
**Pull request by abhiabhi94**
Move all tests to `django` `unittest`

    Some tests that seemed integration tests have now be transformed to unit tests
    Some tests might fail because of the recent changes to the models

The modules used by `pytest` have not yet been deleted for others to view and compare current tests with the present one.
Once this request is ready to merge, we can delete them maybe.
More tests have to be added.
Addresses #175 and #112 #7

### CODE REVIEW

**Comment by abhiabhi94** [comment]
I think we also need to maybe change the name of the file https://github.com/coronasafe/care/blob/master/config/settings/test.py since the command `python manage.py` is unable to detect all the tests from the base directory. I may be completely wrong.

**Comment by vigneshhari** [comment]
@abhiabhi94 we can merge if you are okay with it , we will check each tests when we are free

**Comment by abhiabhi94** [comment]
@vigneshhari Yes i am okay...just make sure I am not responsible for breaking something :-p

**Comment by vigneshhari** [comment]
@abhiabhi94 i will merge the tests, but i changed Travis CI config to use PyTests , once the Django based tests are successful i will switch back, okays?

**Pull request merged**
