### PR TITLE
Add Telemedicine as a rounds type option

### PR DESCRIPTION
**Pull request by Ashesh3**
Frontend Issue: https://github.com/coronasafe/care_fe/pull/6831

## Proposed Changes

- Add Telemedicine as a daily rounds type option

### Associated Issue

- https://github.com/coronasafe/care_fe/issues/6676

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Review by sainak — APPROVED** [review]

**Review by rithviknishad — COMMENTED** [review]
Should we add validation to allow create of telemedicine rounds only if related consultation is DC?

**Comment by Ashesh3** [comment]
> Should we add validation to allow create of telemedicine rounds only if related consultation is DC?
> 
> image

The option is already hidden in the frontend, but I do agree it's a best practice to add a validation here to ensure data consistency.

**Comment by nihal467** [comment]
@Ashesh3 fix the test

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
@vigneshhari can you review this priority PR

**Comment by vigneshhari** [comment]
Something feels off about the migration, why is it showing that a migration was edited , cc @sainak

**Comment by Ashesh3** [comment]
> Something feels off about the migration, why is it showing that a migration was edited , cc @sainak

While resolving a merge conflict with the migration, I might have moved one of the previous migrations after this PR's migration 😅 . I've fixed that, should be fine now. could you review?

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
