### PR TITLE
Modified JSON schema of daily rounds

### PR DESCRIPTION
**Pull request by sam9111**
Added "concentration" of type number and "conc_unit" of type string to INFUSION schema
Added "calories" of type number to FEED schema

### CODE REVIEW

**Comment by gigincg** [comment]
@sam9111 add a description for the PR😅

**Review by gigincg — CHANGES_REQUESTED** [review]
If you make concentration and conc unit required, you won't be able to make it optional later

**Comment by gigincg** [comment]
Calories also can't be a required field. There's a possibility of the nurses not knowing the right value. This would mean they'll enter wrong or placebo values 

@sam9111

**Comment by sam9111** [comment]
will create a new PR for this one

**Pull request closed without merging**
