### PR TITLE
add tests and validation for filterset

### LINKED ISSUE #2580: Add Input Validation for /patient API Search Parameters
Update the `/patient` API to incorporate input validation on search parameters, ensuring user inputs conform to defined limits. 

For instance, the `name` field currently accepts up to 200 characters, but the search functionality inadvertently allows more. 

We should also verify the same for all other supported fields. 

Also the api should be `/patients` instead of `/patient` right? 🤔

### PR DESCRIPTION
**Pull request by praffq**
## Proposed Changes

# Added Validations in the Updated `PatientFilterSet`

1. **`name`**
   - **Validation**: `max_length=200`
   - **Purpose**: Limits the `name` field to a maximum of 200 characters.

2. **`age`**, **`age_min`**, and **`age_max`**
   - **Validation**: `validators=[MinValueValidator(0)]`
   - **Purpose**: Ensures ages provided for filtering are non-negative (minimum value of 0).

3. **`srf_id`**
   - **Validation**: `max_length=200`
   - **Purpose**: Limits the `srf_id` field to a maximum of 200 characters.

4. **`district_name`**, **`local_body_name`**, and **`state_name`**
   - **Validation**: `max_length=255`
   - **Purpose**: Limits these location-related fields to a maximum of 255 characters.

5. **`covin_id`**
   - **Validation**: `max_length=15`
   - **Purpose**: Limits the `covin_id` field to a maximum of 15 characters.

6. **`number_of_doses`**
   - **Validation**: `validators=[MinValueValidator(0), MaxValueValidator(3)]`
   - **Purpose**: Ensures the number of vaccine doses is within the range 0 to 3 (inclusive).

### Associated Issue

- Fixes #2580 

## Merge Checklist

- [x] Tests added/fixed
- [x] Linting Complete

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

## Summary by CodeRabbit

- **New Features**
	- Enhanced patient filtering with improved validation for phone numbers, names, gender, age, and other fields.
  
- **Bug Fixes**
	- Implemented error handling for invalid query parameters, ensuring appropriate responses for user input errors.

- **Tests**
	- Introduced new test cases to validate error handling for invalid parameters, including name length, gender choices, age constraints, and identifier lengths.

### CODE REVIEW

**Comment by praffq** [comment]
test cases depends on #2591

**Comment by praffq** [comment]
> test cases depends on https://github.com/ohcnetwork/care/issues/2591

Removing the phone number validations from backend since we have a check for it in frontend

**Review by rithviknishad — APPROVED** [review]

**Review by sainak — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
> > test cases depends on #2591
> 
> Removing the phone number validations from backend since we have a check for it in frontend

Doesn't look like FE validation is working for all cases (which we should adjust), but might as well keep BE validation, no? Checkout [9010](https://github.com/ohcnetwork/care_fe/issues/9010).

**Comment by praffq** [comment]
@Jacobjeevan the issue https://github.com/ohcnetwork/care_fe/issues/9010 should be fixed with #2591  , we will need better validations instead of regex matching that we are currently using in BE and FE

**Comment by bodhish** [comment]
@vigneshhari can you review this?

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
