### PR TITLE
Refactor Symptoms

### PR DESCRIPTION
**Pull request by Ashesh3**
Frontend issue: https://github.com/coronasafe/care_fe/issues/4662

The changes made in this PR are as follows:

- Vomiting and Diarrhoea have been separated as two different symptoms
- Vomiting/Diarrhoea has been migrated to Vomiting
- Diarrhoea has been added as a new symptom
- SARI has been removed from the list
- The following symptoms have been added: Pain, Pedal Edema, Wound, Constipation and Head Ache.

### CODE REVIEW

**Comment by vigneshhari** [comment]
Needs an ops review because changing this would change all data that we currently have.

**Comment by aparnacoronasafe** [comment]
Please go ahead. 

@Ashesh3 Could you also add "Bleeding" and "DIZZINESS" to list of symptoms?

You can decide whether to do it here or take it as a separate issue

**Comment by Ashesh3** [comment]
> Please go ahead.
> 
> @Ashesh3 Could you also add "Bleeding" and "DIZZINESS" to list of symptoms?
> 
> You can decide whether to do it here or take it as a separate issue

@aparnacoronasafe I've added:

```
    (23, "BLEEDING"),
    (24, "DIZZINESS"),
```

**Review by vigneshhari — APPROVED** [review]

**Comment by vigneshhari** [comment]
Merging after ops confirmation

**Pull request merged**
