### PR TITLE
feat(*) - add authentication through jwt. fixes #17.

### LINKED ISSUE #17: need a current user endpoint.

### PR DESCRIPTION
**Pull request by tucosaurus**
Also solves #17

### CODE REVIEW

**Comment by tucosaurus** [comment]
@vigneshhari Browsable Api works through [session authentication](https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication). In the event that we want to merge this in. Where should I add the api docs ?

**Comment by vigneshhari** [comment]
Before we definitely switch to JWT's i wanted to have a talk with the front end folks to see what they are comfortable with so that there are no issues. That is causing a delay, for the time being, we can create a sample class for API's and let all our API Views Extend that, so if we wanted to add JWT's it would be really simple to do so. Until Then let's Continue with session-based auth.

**Comment by vigneshhari** [comment]
If we work with DRF only then we can generate API docs with swagger, the front end folks would be happier too.

**Comment by tomahawk-pilot** [comment]
@vigneshhari @tucosaurus we also welcome jwt

**Comment by vigneshhari** [comment]
Created Another PR and Merged

**Pull request closed without merging**
