### PR TITLE
Add type to ambulance model

### PR DESCRIPTION
**Pull request by NavenAllen**
Related Issue: #83

### CODE REVIEW

**Comment by biswaz** [comment]
Please add a default value, so that existing data will be migrated using that value. Also you should add the migration file along with the PR

**Comment by vigneshhari** [comment]
@NavenAllen Please rebase and make the changes ASAP

**Comment by NavenAllen** [comment]
@biswaz @vigneshhari Made the changes, rebased and pushed

**Comment by vigneshhari** [comment]
Reviewing

**Pull request merged**
