### PR TITLE
Facility view redesign

### PR DESCRIPTION
**Pull request by yahya31415**
image

### CODE REVIEW

**Comment by rejuls** [comment]
@yahya31415 Is it resposive? You can make it better using the classes from tailwind css. https://tailwindcss.com/components

After that, make a pull and fix the merge conflicts and do a fresh PR. I won't work on this file for now.

**Comment by yahya31415** [comment]
Okay, Will do

**Comment by rejuls** [comment]
Also check last part of #13

**Comment by yahya31415** [comment]
On it

**Comment by rejuls** [comment]
Do pull frequently as well, lots of people working now.

**Comment by rejuls** [comment]
@yahya31415 use the same card classes on care/templates/facility/facilities_view.html as well. Details on #13

**Comment by yahya31415** [comment]
Okay

**Pull request closed without merging**
