### PR TITLE
update main CI

### LINKED ISSUE #754: Update Dockerfile
Merge base dockerfile into main dockerfile and add layer caching in github actions

### PR DESCRIPTION
**Pull request by sainAk**
closes #754

Test runs:
https://github.com/sainAk/care/actions/runs/2353150113
https://github.com/sainAk/care/actions/runs/2353180345

### CODE REVIEW

**Review by tomahawk-pilot — APPROVED** [review]

**Comment by tomahawk-pilot** [comment]
@vigneshhari have a look and merge when you are ready

**Comment by sainAk** [comment]
Requires #724 for static files

**Comment by vigneshhari** [comment]
@tomahawk-pilot is this good to go ?

**Comment by sainAk** [comment]
For now I'm only building the docker image, after we add localstack we can switch over to compose for testing.

**Pull request merged**
