### PR TITLE
Disable browser suggestions in user signup form

### LINKED ISSUE #48: Disable suggestion for input fields.
On Mac OS, the suggestion model is stuck 🙄. 

IMG_20200322_113952

### PR DESCRIPTION
**Pull request by Kailaash-Balachandran**
Fixes #48 : 
1. Disable suggestion for input fields (except the first name, last name, and phone number)
2. Use Crispyform helper to render form fields.

### CODE REVIEW

**Comment by vigneshhari** [comment]
why was the placeholders removed while adding the autocomplete fields ?

**Comment by Kailaash-Balachandran** [comment]
> why was the placeholders removed while adding the autocomplete fields ?

Placeholders were unused in the template (https://care.coronasafe.network/users/signup/staff/). 

Previously, the form was rendered with `{{ form|crispy }}`, which doesn't use the form helper methods. This PR proposes to use `{% crispy form %}` instead to render the helper methods. 

However, if placeholders are required, I can add them back.

**Comment by vigneshhari** [comment]
@rejuls check if the UI is rendering fine , if so Merge.

**Comment by rejuls** [comment]
@Kailaash-Balachandran did you test the form after the changes? I think with the crispy forms tag require the submit button to be passed from the form class and not inside the template. Can you check if data is being POST?

**Comment by Kailaash-Balachandran** [comment]
> @Kailaash-Balachandran did you test the form after the changes? I think with the crispy forms tag require the submit button to be passed from the form class and not inside the template. Can you check if data is being POST?

@rejuls  Great catch. I've now added `self.helper.form_tag = False` in the helper. Also, tested.

**Pull request merged**
