### PR TITLE
Improved GitHub Actions pipeline: parallel ARM and x86 builds

### LINKED ISSUE #1803: Make arm and x86 builds run parallelly
Sequentially building both takes more than 8 minutes.
Improve our github actions pipeline to run builds in separate jobs

### PR DESCRIPTION
**Pull request by ghost**
## Proposed Changes

- This PR improves the GitHub Actions pipeline by running ARM and x86 builds in parallel using the matrix strategy. 

### Associated Issue

- Fixes #1803 

### Testing:
- Tested locally using Docker Buildx with `linux/amd64` and `linux/arm64` platforms.
- Verified that the builds are running in parallel.
  

Screenshot from 2024-10-22 00-22-03

Screenshot from 2024-10-22 01-02-24

- Here is a log output showing parallel builds:

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

### CODE REVIEW

**Comment by ghost** [comment]
Hey @rithviknishad sir, even though builds are running parallely when I am testing the workflows on my repo in both branches develop & PR branch I am getting almost same time duration 

Screenshot from 2024-10-22 01-32-13

**Review by rithviknishad — APPROVED** [review]

**Comment by vigneshhari** [comment]
@sainak take a look

**Comment by sainak** [comment]
@Alokih thanks for the pr however this is not the correct way to publish multiplatform images, and from my research I found that buildkit already does some parallelization during builds, so the benefits of matrix builds are negligible in the case of just 2 platforms.

**Comment by ghost** [comment]
Ok @sainak sir

**Pull request closed without merging**
