### PR TITLE
Bed Capacity Form Validation #53

### PR DESCRIPTION
**Pull request by basitht16**

### CODE REVIEW

**Comment by justinjohnymathew** [comment]
@basitht16  this validates only when already existing bed capacity is updated.

**Comment by basitht16** [comment]
Updated please check

**Comment by vigneshhari** [comment]
@rejuls please review

**Comment by rejuls** [comment]
@basitht16 , all cases tested right?

**Comment by basitht16** [comment]
@rejuls Yes

**Comment by rejuls** [comment]
fixes #53

**Pull request merged**
