### PR TITLE
Add list and detail serializer to facility_asset module

### PR DESCRIPTION
**Pull request by GeekGawd**
## Proposed Changes

- Added List Serializer to only include the necessary fields during List Call of Frontend
- Added Detail Serializer for detailed view

## Associated Issue

Part of https://github.com/coronasafe/care_fe/issues/5492

## Merge Checklist

- [x] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Comment by sainak** [comment]
@GeekGawd  the changes look good, can you verify and remove the AssetSerializer from other places as well
Note: the AssetSerializer is also used to fetch data [here](https://github.com/coronasafe/care_dashboard/blob/master/src/pages/asset/AssetDetails.tsx#L31) using the `public/asset/` endpoint, this looks like it could be handled by the AssetDetailSerializer 

and for the tests you can add and validate more data.

**Comment by GeekGawd** [comment]
@sainak I don't think there exists a file named AssetDetail.tsx

**Review by sainak — CHANGES_REQUESTED** [review]
changes requested

**Comment by GeekGawd** [comment]
@sainak done please check

**Comment by GeekGawd** [comment]
@sainak yep fixed it

**Comment by sainak** [comment]
Looks good, just add a todo [here](https://github.com/coronasafe/care/pull/1427/files#diff-e81f72006459ce5c1245abbb101a1345e909b90ec7211585c02a44a232e0a0cfR63) to remove when remove serializers are updated

**Review by sainak — APPROVED** [review]

**Comment by sainak** [comment]
@GeekGawd resolve confilicts

**Comment by GeekGawd** [comment]
@sainak merged and fixed test cases

**Review by sainak — APPROVED** [review]

**Pull request closed without merging**
