### PR TITLE
Added KSDMA logo, updated footer text

### PR DESCRIPTION
**Pull request by afeedh**

### CODE REVIEW

**Comment by rejuls** [comment]
Desktop and mobile screenshots please

**Comment by bodhish** [comment]
Don't merge. Need few more changes.

**Comment by afeedh** [comment]
screenshot_20200322_141013
screenshot_20200322_141041
screenshot_20200322_141058

**Comment by bodhish** [comment]
Please update the footer text to

CoronaSafe Network is an open-source public utility designed by a multi-disciplinary team of innovators and volunteers who are working on a model to support Government efforts with full understanding and support of Government of Kerala

Include link to our github.com org

**Comment by afeedh** [comment]
> Please update the footer text to
> 
> CoronaSafe Network is an open-source public utility designed by a multi-disciplinary team of innovators and volunteers who are working on a model to support Government efforts with full understanding and support of Government of Kerala
> 
> Include link to our github.com org

LInk to github.com/coronasafe/ or github.com/coronasafe/care ?

**Comment by rejuls** [comment]
Change link to https://github.com/coronasafe. Also do a pull and fix any merge issues.

**Comment by rejuls** [comment]
Also add equal padding above and below logo. Use py class

**Comment by afeedh** [comment]
> Change link to https://github.com/coronasafe. Also do a pull and fix any merge issues.

PR updated.

screenshot_20200322_184212

**Comment by rejuls** [comment]
Screenshots please 😁

**Comment by afeedh** [comment]
> Screenshots please

screenshot_20200322_184651
screenshot_20200322_184703

**Comment by rejuls** [comment]
Footer container in desktop view is getting shorter in width now. Make it back to container-fluid as it was before.

**Comment by afeedh** [comment]
> Footer container in desktop view is getting shorter in width now. Make it back to container-fluid as it was before.

Should I change the width span of p block as well? I think the it might look odd as the text might span the whole width in desktop.

screenshot_20200322_190423

screenshot_20200322_190408

**Comment by vigneshhari** [comment]
@rejuls you can make the required changes and merge the changes.

**Comment by rejuls** [comment]
@afeedh , Looks good. Fix #50

**Pull request merged**
