### PR TITLE
Add option to filter users with no home facility

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Allows you to filter users with no home facility assigned.

### Associated Issue

- Backend PR for https://github.com/coronasafe/care_fe/issues/8038

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 functionality looks good, for backend review, even though the frontend is having a small state management issue

**Comment by shivankacker** [comment]
@nihal467 fixed frontend issue

**Review by rithviknishad — COMMENTED** [review]
LGTM, tests needed

**Comment by nihal467** [comment]
LGTM , @shivankacker can you look into rithvik's comment

**Review by sainak — APPROVED** [review]
LGTM, just test what happens if the value is not a valid uuid

**Comment by shivankacker** [comment]
@nihal467 @sainak Tests added

**Review by rithviknishad — APPROVED** [review]

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
