### PR TITLE
Fix: Add get_object_or_404 to resolve 500 DoesNotExist Error and added tests

### LINKED ISSUE #1348: PatientConsultation.DoesNotExist: PatientConsultation matching query does not exist.  `/api/v1/consultation/{consultation_external_id}/daily_rounds/analyse/`
Sentry Issue: [CARE-NH](https://coronasafe-network.sentry.io/issues/4223367714/?referrer=github_integration)

stacktrace

```python
PatientConsultation.DoesNotExist: PatientConsultation matching query does not exist.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "dry_rest_permissions/generics.py", line 128, in has_permission
    return model_class.has_write_permission(request)
  File "care/facility/models/daily_round.py", line 502, in has_write_permission
    return DailyRound.has_read_permission(request)
  File "care/facility/models/daily_round.py", line 506, in has_read_permission
    consultation = PatientConsultation.objects.get(
  File "django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
 ```

### PR DESCRIPTION
**Pull request by GeekGawd**
## Proposed Changes

- Changed .get to get_object_or_404 to fetch PatientConsultation from external consultation id.
- Added tests to verify the behaviour

Kindly review the linting as I have not done that.

### Associated Issue
 Fixes #1348 
@coronasafe/code-reviewers

## Merge Checklist

- [x] Tests added/fixed
- [x] Update docs in `/docs`
- [x] Linting Complete

### CODE REVIEW

**Review by vigneshhari — APPROVED** [review]
LGTM

**Comment by vigneshhari** [comment]
Fix the linting before the MR is merged

**Comment by GeekGawd** [comment]
@vigneshhari  okay sir, i have fixed the linting issues and checked against the .flake8 configuration

**Comment by sainak** [comment]
@GeekGawd the lint is still failing, you need to install pre-commit before contributing to this repo
for now, you can run `pre-commit run --files $(git diff --name-only master...HEAD)`

**Comment by vigneshhari** [comment]
@GeekGawd you can drop the sir! we are all contributors here 😅

**Comment by GeekGawd** [comment]
@sainak Aight, Thank You! Got my problem, I was just running flake8, the isorts tests kept failing. Now they are resolved with your command. Thank You!

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
