### PR TITLE
Change disease status from recovery to recovered

### PR DESCRIPTION
**Pull request by abhiabhi94**
- inside the PatientRegistration model.

closes #541

### CODE REVIEW

**Comment by vigneshhari** [comment]
The Recovery Option should be deleted as well.

**Comment by vigneshhari** [comment]
Let's close the other PR and move all the changes here.

**Comment by abhiabhi94** [comment]
> The Recovery Option should be deleted as well.

If we remove the `RECOVER` option, how will the migrations and the test use that value? I think we can probably alias them through a method inside the model's `save` method maybe?

**Comment by vigneshhari** [comment]
@abhiabhi94 we can remove it after the migration is performed right ? as another migration?

**Comment by abhiabhi94** [comment]
> @abhiabhi94 we can remove it after the migration is performed right ? as another migration?

not really, because it will create issues at other places when the migration is run. If the value `RECOVERED` is not present inside the codebase, when the migrations is run at some other place(consider the migration was first run successfully on my end and then, after removing the thing,  you too try to run it at your end), it will throw an error.

I think aliases it should be sufficiently enough for this use case.

**Comment by abhiabhi94** [comment]
The tests for the current change are passing as of now at my end. 

`black`, `isort`, `autoflake` etc. hooks seem to have made some changes that might make the `diff` a bit more than it should have been.

If this look good enough, feel free to merge.

**Pull request merged**
