### PR TITLE
Add LocalBody model to Django Admin

### PR DESCRIPTION
**Pull request by agzuniverse**
If there is no particular reason why this model is not available in Django Admin, this change would be useful for debugging and adding data using Django Admin.

### CODE REVIEW

**Comment by anroopak** [comment]
This is being added in the following PR.

**Comment by anroopak** [comment]
Considering that we are not merging the earlier said PR, this may be merged.  @vigneshhari

**Comment by anroopak** [comment]
@agzuniverse Hey, this was solved in #105 please confirm :)

**Comment by agzuniverse** [comment]
Yes it does. Closing now.

**Pull request closed without merging**
