### PR TITLE
Centralise linting across project

### LINKED ISSUE #1255: Centralise Linting across the project
Currently, the linting for Care is all over the place, PR's with a single line change end up making 100+ diffs,  
Create a PR that fixes all linting issues WRT the current linter config
Ensure linting pipelines fail when the project code is not in the right format.

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- ran `black .` and `isort .`

### Associated Issue
  - fixes #1255
 
@coronasafe/code-reviewers

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete

### CODE REVIEW

**Comment by rithviknishad** [comment]
@vigneshhari those are flake8 lints. it'll require manually modifying the code. There's like 150 such modifications required :) 

image

**Comment by vigneshhari** [comment]
@rithviknishad we need to fix those as well 😓 otherwise we can't use the pipeline to ensure that the code is in the right format all the time

**Comment by vigneshhari** [comment]
Move Exception to BaseException and remove unused variables/imports/unused f strings. I will fix the rest of them.

**Comment by cp-Coder** [comment]
Closing this PR as I am not able to push the changes on this branch

**Pull request closed without merging**
