### PR TITLE
add state, district, local body models

### PR DESCRIPTION
**Pull request by anroopak**
Related Issue: https://github.com/coronasafe/care/issues/99

### CODE REVIEW

**Comment by vigneshhari** [comment]
We also have to populate all the data in Kerala, possibly in Malayalam too, write management commands for this and use a json data dump. Also when we port the existing data how will we figure out the local body date

**Comment by afzalIbnSH** [comment]
> Also when we port the existing data how will we figure out the local body date
Put `Panchayath` as default ?

**Comment by vigneshhari** [comment]
we still need the panchayath data right ?

**Comment by vigneshhari** [comment]
how do we say that this hospital comes under X Panchayath

**Comment by anroopak** [comment]
We currently cannot figure out the local body without information from data entry team. So we can match then against a default panchayath and then when data entry comes in, we can update it. 

Second way is that we match only district fields now, leave local body as blank for now. And once data is in, we can map them.

**Comment by anroopak** [comment]
Ambulance currently uses District, should that also be changed to Panchayaths?

**Comment by vigneshhari** [comment]
Everything that uses Districts should be changed to this model, for Ambulances lets keep with just the district Table.

**Comment by vigneshhari** [comment]
leaving them blank is good for now

**Comment by vigneshhari** [comment]
Tmrw i will bring someone from open street map so we can correctly map the structure of the location and get a reliable source of data to populate them as well, Okay ?

**Comment by anroopak** [comment]
@vigneshhari added models and initial data migration. This is the first PR as part of the plan mentioned here - https://github.com/coronasafe/care/issues/99#issuecomment-604030314

**Comment by vigneshhari** [comment]
@anroopak we will block it until we can populate all the Lower Level Government details, will get it by tmrw noon, @tomahawk-pilot , we will NULL the lower level govt for the migrated data, We also have to open up API's for getting districts from states, panchayaths from districts and states and so on for the React Guys to shift properly.

**Comment by tomahawk-pilot** [comment]
https://github.com/rebuildearth/data/tree/master/data/india/kerala/lsgi_site_data

**Comment by vigneshhari** [comment]
@anroopak check if we can use this data and it agrees with our database model

**Comment by anroopak** [comment]
@vigneshhari Yes, this looks fine. We can go ahead and populate based on this JSON. That can be done seperately.

**Comment by vigneshhari** [comment]
@anroopak write a management command that syncs the json to the database model then, so its easier for us

**Comment by anroopak** [comment]
@vigneshhari Can we merge this?

**Comment by biswaz** [comment]
Still needs a data migration/one time script to populate lsgb data to the d. I prefer a data migration.

**Pull request merged**
