### PR TITLE
ICD-11 diagnosis cannot be both provisional and final

### PR DESCRIPTION
**Pull request by GokulramGHV**
## Proposed Changes

- Raised error when a diagnosis is in both provisional and final diagnosis list

### Associated Issue

- coronasafe/care_fe#6366

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Add tests

**Review by rithviknishad — CHANGES_REQUESTED** [review]
The tests need to pass too :)

**Review by rithviknishad — APPROVED** [review]
@sainak should we move the loading of icd11 to in-memory for tests to somewhere else? 

or is it fine for now since we'll soon rewrite how we populate icd11/medibase to in memory in the first place?

**Review by sainak — APPROVED** [review]

**Comment by sainak** [comment]
> @sainak should we move the loading of icd11 to in-memory for tests to somewhere else?
> 
> or is it fine for now since we'll soon rewrite how we populate icd11/medibase to in memory in the first place?

it's fine for now

**Comment by nihal467** [comment]
lgtm @vigneshhari can you review it

**Comment by rithviknishad** [comment]
The model changes from https://github.com/coronasafe/care/issues/1574 will naturally solve the related issue.

**Pull request closed without merging**
