### PR TITLE
Added migrations to add skills to db

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- Added migration to add specialization skills to the database

cc: @mathew-alex 

### Associated Issue
  - None

### Architecture changes
  - None
 
@coronasafe/code-reviewers

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete

### CODE REVIEW

**Comment by vigneshhari** [comment]
Since you are making changes to the skill, could you make skill name unique and add exception handling to the MR you currently have

**Comment by khavinshankar** [comment]
@vigneshhari can you recheck this again

**Review by mathew-alex — APPROVED** [review]

**Comment by vigneshhari** [comment]
You are deleting all skills here, only duplicates have to be deleted, this inadvertently deletes all user-skill objects

**Comment by khavinshankar** [comment]
@vigneshhari we don't actually give any API for the users to add any skills, This is the first time we are adding skills, will this still be a problem?

**Pull request merged**
