### PR TITLE
chore: Add total doctors count to hospital doctor list response

### LINKED ISSUE #2628: Backend for Auto-scroll Issue and Total Count Card for Staff Capacity Pagination in facility details page
**Bug Description:**  
Auto-scroll behavior and incorrect total count display for staff capacity pagination in the facility details page.  

**Steps to Reproduce:**  
1. Go to the facility details page.  
2. Add or update staff capacity.  
3. Observe auto-scroll behavior.  
4. Check the total capacity card for incorrect count (shows current page only).  

**Expected Behavior:**  
- Auto-scroll should stop at the staff capacity section instead of the page's top.  
- Total capacity card should display the total staff capacity across all pages.  

**Screenshots/Recordings:** 

https://github.com/user-attachments/assets/1b04ecb1-ef59-4638-a177-87a36a463853

**Additional Context:**  
Fix reference Frontend: [[Issue #9122](https://github.com/ohcnetwork/care_fe/issues/9122)]
Fix reference Frontend Pull Request: [[PR #9275](https://github.com/ohcnetwork/care_fe/pull/9275)]

### PR DESCRIPTION
**Pull request by shauryag2002**
## Proposed Changes

- fixes #2628 
- Auto-scroll should stop at the staff capacity section instead of the page's top.
- Total capacity card should display the total staff capacity across all pages.

### Associated Issue

- Fix reference Frontend: [[Issue #9122](https://github.com/ohcnetwork/care_fe/issues/9122)]
- Fix reference Frontend Pull Request: [[PR #9275](https://github.com/ohcnetwork/care_fe/pull/9275)]

https://github.com/user-attachments/assets/d34b76ef-dd5f-4a0e-8775-9fd7de7c9008

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

## Summary by CodeRabbit

- **New Features**
	- Introduced a new read-only field, `total_doctors`, displaying the total count of doctors associated with a facility.
	- Enhanced data representation with a customized output method for better clarity on doctor counts.

### CODE REVIEW

**Comment by shauryag2002** [comment]
@coderabbitai full review

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Change in serializer instead. Changing here does not show up in the API docs.

Also I don't think this is the right solution to do this.

cc @sainak / @vigneshhari

**Comment by shauryag2002** [comment]
@coderabbitai full review

**Comment by shauryag2002** [comment]
@coderabbitai full review

**Comment by shauryag2002** [comment]
> Change in serializer instead. Changing here does not show up in the API docs.
> 
> Also I don't think this is the right solution to do this.
> 
> cc @sainak / @vigneshhari

@rithviknishad , Now changes will show up in API docs and changed in serializer only now.
image

**Comment by bodhish** [comment]
Closing in favour of https://github.com/ohcnetwork/care_fe/pull/9436

**Pull request closed without merging**
