### PR TITLE
converted investigation and investigation group data into JSON

### PR DESCRIPTION
**Pull request by DraKen0009**
## Proposed Changes

- converted the data present populate_investigation.py from string to json

### Associated Issue

- #1541 

## Merge Checklist

- [x] tested using python manage.py populate_investigations

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Keep the data outside of the python code in a JSON file. (Like how we have for ICD11 and Medibase)

**Comment by DraKen0009** [comment]
@rithviknishad  made the required changes , please have a look

**Comment by DraKen0009** [comment]
@sainak  do we need to update the data according to comment before ?
image

Updated to - 
image

**Comment by DraKen0009** [comment]
Also the data at the bottom of the table is not accurate (min, max values)
image

I can update them accordingly and update the json file with it.

**Comment by sainak** [comment]
@DraKen0009 the rows marked yellow needs to be updated, and the ones marked red needs to be deleted

>Also the data at the bottom of the table is not accurate (min, max values)
which rows are you referring to?

**Comment by DraKen0009** [comment]
135-145 ( what i have currently noticed)

- like in line 135 
Min should be 11 and max should be 18
But given 0 and 25

**Comment by sainak** [comment]
> 135-145 ( what i have currently noticed)
> 
>     * like in line 135
>       Min should be 11 and max should be 18
>       But given 0 and 25

I think what you are referring to is ideal value, that is its mentioned in the col just before min, which needs to be added in the model as well, min and max look okay to me

**Review by sainak — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Review by vigneshhari — APPROVED** [review]

**Review by sainak — CHANGES_REQUESTED** [review]
TODO:
- make investigation names unique, and add suffix to duplicate values in db
- find and rename duplicates in data/investigations.json
- use upsert to create or update data

**Review by sainak — APPROVED** [review]

**Comment by sainak** [comment]
@rithviknishad review required

**Review by rithviknishad — APPROVED** [review]

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
