### PR TITLE
Switch investigation default from `dict` to `list` and remove deprecated `prescriptions`

### LINKED ISSUE #8008: TypeError: s.map is not a function in InvestigationBuilder component
An error was encountered in the `InvestigationBuilder` component causing the JavaScript TypeError: `s.map is not a function`. This error is likely due to attempting to call `.map()` on a variable `s` that is not properly initialized as an array before this method call.

#### Error Details
- **File**: `InvestigationBuilder.tsx`
- **Function**: `InvestigationBuilder`
- **Error Message**: `TypeError: s.map is not a function`
- **Sentry Event ID**: `3533b1853bd646609326b51cf152345a`

#### Steps to Reproduce:
1. Navigate to the URL: `https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/19adff46-588e-4072-89b3-a23ec1dec5fa/consultation/cc5ec4c3-94af-4fec-a954-fb9b7c45b89e/daily-rounds`
2. Error triggers when the component attempts to render based on fetched data that presumably includes an incorrectly formatted `s` variable.

#### Potential Cause:
The variable `s` might be either `undefined` or not an array at the time `.map()` is called. This could be due to a failure in data fetching or data transformation before passing it to the `InvestigationBuilder`.

#### Suggested Fix:
- Ensure `s` is always initialized as an array.
- Add error handling to check the type of `s` before applying array-specific methods like `.map()`.

This issue has occurred in a staging environment, so it's crucial to address it before the next production deployment to prevent user-facing errors and potential disruptions in service.

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Use `list` as default for `PatientConsultation.investigation` instead of `dict`
- Custom migration to update existing data
- Remove the unused deprecated `prescriptions` column from PatientConsultation model and `medication_given` (prescriptions) from Daily Rounds model which was missing from #2247

### Associated Issue

- Resolves https://github.com/ohcnetwork/care_fe/issues/8008

## Merge Checklist

- [x] Tests added/fixed
- [x] Update docs in `/docs`
- [x] Linting Complete
- [x] Any other necessary step

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

### CODE REVIEW

**Review by sainak — APPROVED** [review]

**Comment by nihal467** [comment]
@sainak @vigneshhari  docker compose exec backend bash -c "python manage.py populate_investigations" command is not working in docker app windows

**Comment by rithviknishad** [comment]
@nihal467 could you share more details on what the error is? Unable to replicate.

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
> @nihal467 could you share more details on what the error is? Unable to replicate.

the PR is working well, it's just the investigation loading command for docker is not working, but loaded them using some alternative way aakash suggested and the PR is good to be merged

**Review by shivankacker — APPROVED** [review]

**Review by anroopak — APPROVED** [review]

**Review by sainak — APPROVED** [review]

**Pull request merged**
