### PR TITLE
Updated occupation field for text support

### LINKED ISSUE #806: Add occupation field in patient model
Part of https://github.com/coronasafe/care_fe/issues/2588

### PR DESCRIPTION
**Pull request by Marmik2003**
fixes #806

### CODE REVIEW

**Comment by vigneshhari** [comment]
Migrations make no sense, since there are unrelated changes

**Comment by aparnacoronasafe** [comment]
@Marmik2003 can you make the changes and close this ASAP? been pending for a long time

**Comment by gigincg** [comment]
@Marmik2003 Update the migration ASAP. This has been stale for way too long!

**Comment by cp-Coder** [comment]
This issue will be fixed in PR#1000

**Comment by cp-Coder** [comment]
This issue will be fixed by PR coronasafe/care#1000

**Pull request closed without merging**
