### PR TITLE
implementing manual logic of on_delete option in M2M models 

### LINKED ISSUE #1330: Manually cascade delete M2M models when related model is deleted.
**Describe the bug**
Currently, most M2M models are not deleted when their related model is deleted. The `on_delete` doesn't take effect as we use soft delete for all the models that inherits from `BaseModel`.

**Expected behavior**
`ModelAB` should be updated to `deleted=True` when `ModelA` or `ModelB` is deleted.

### Many to Many models in CARE that are potentially having this issue.

- [ ] `UserDefaultAssetLocation`
- [ ] `FacilityDefaultAssetLocation`
- [x] `AssetBed` #1322
- [ ] `ConsultationBed`
- [ ] `FacilityUser`
- [ ] `InvestigationValue`
- [ ] `PatientSample`

### PR DESCRIPTION
**Pull request by yaswanthsaivendra**
## Proposed Changes

- Implementing on_delete logic in below M2M models as it doesnt work coz of our soft delete logic.

- [x] UserDefaultAssetLocation ( Implements soft delete logic on - [AsseLocation](https://github.com/coronasafe/care/pull/1344/files#diff-3c5b2ba13657bd45e4ceb4d1df1c1951b0746d651571c8ee411f8fd11315b754R43) , [User](https://github.com/coronasafe/care/pull/1344/files#diff-2ba3d7245d12428858fa70a8f6818ba4560a3dd561c4a5934e6b1b19cc64abefR349) )
- [x]  FacilityDefaultAssetLocation ( Implements soft delete logic on - [AssetLocation](https://github.com/coronasafe/care/pull/1344/files#diff-3c5b2ba13657bd45e4ceb4d1df1c1951b0746d651571c8ee411f8fd11315b754R44), [Facility](https://github.com/coronasafe/care/pull/1344/files#diff-6e7c0444aaf885a9471092dad39cdafcf8f1c93fcfe96a4a4a84715310a2a3caR203) )
- [x]  ConsultationBed ( Implements soft delete logic on - [Bed](https://github.com/coronasafe/care/pull/1344/files#diff-35c5c238c7c77b31aea84bc457a5ddfe2033661fd9d2e855cacc30539f5e9b74R55), [PatientConsultation](https://github.com/coronasafe/care/pull/1344/files#diff-5f86d36c9415c5c40e8820c1e4f86aa28dd713d6a74a1adc1f387598b8b542b9R239) )
- [x] FacilityUser ( Implements soft delete logic on - [Facility](https://github.com/coronasafe/care/pull/1344/files#diff-6e7c0444aaf885a9471092dad39cdafcf8f1c93fcfe96a4a4a84715310a2a3caR204) , [user](https://github.com/coronasafe/care/pull/1344/files#diff-2ba3d7245d12428858fa70a8f6818ba4560a3dd561c4a5934e6b1b19cc64abefR350), [created_by](https://github.com/coronasafe/care/pull/1344/files#diff-2ba3d7245d12428858fa70a8f6818ba4560a3dd561c4a5934e6b1b19cc64abefR351) )
- [x] InvestigationValue ( Implements soft delete logic on - [PatientConsultation](https://github.com/coronasafe/care/pull/1344/files#diff-5f86d36c9415c5c40e8820c1e4f86aa28dd713d6a74a1adc1f387598b8b542b9R240), [PatientInvestigationGroup](https://github.com/coronasafe/care/pull/1344/files#diff-63a6c0ad8aa86f3e7127e68ff7f15fa2fa4dcc50e0ca984f2df791f915c3d18fR19), [PatientInvestigation](https://github.com/coronasafe/care/pull/1344/files#diff-63a6c0ad8aa86f3e7127e68ff7f15fa2fa4dcc50e0ca984f2df791f915c3d18fR40), [InvestigationSession](https://github.com/coronasafe/care/pull/1344/files#diff-63a6c0ad8aa86f3e7127e68ff7f15fa2fa4dcc50e0ca984f2df791f915c3d18fR63) )
- [x] PatientSample ( Implements soft delete logic on - [PatientRegistration](https://github.com/coronasafe/care/pull/1344/files#diff-b3f06fd122fefa29f2d19434d6bc0c78c00a211729b13113191f108170241420R515), [PatientConsulation](https://github.com/coronasafe/care/pull/1344/files#diff-5f86d36c9415c5c40e8820c1e4f86aa28dd713d6a74a1adc1f387598b8b542b9R241) and set NULL to [created_by](https://github.com/coronasafe/care/pull/1344/files#diff-2ba3d7245d12428858fa70a8f6818ba4560a3dd561c4a5934e6b1b19cc64abefR352), [last_edited_by](https://github.com/coronasafe/care/pull/1344/files#diff-2ba3d7245d12428858fa70a8f6818ba4560a3dd561c4a5934e6b1b19cc64abefR353) of User Model , [Facility](https://github.com/coronasafe/care/pull/1344/files#diff-6e7c0444aaf885a9471092dad39cdafcf8f1c93fcfe96a4a4a84715310a2a3caR205) )

- For  relations having models.CASCADE and models.PROTECT - I implemented soft delete logic
- For relations having models.SET_NULL - I set them to NULL 

### Associated Issue
  - Fixes #1330 
 
@coronasafe/code-reviewers

### CODE REVIEW

**Comment by yaswanthsaivendra** [comment]
@rithviknishad  Review please!

**Review by rithviknishad — CHANGES_REQUESTED** [review]
You are performing `<QuerySet>.delete()`. However, we've overridden the `<Instance>.delete()` to soft delete only. 
Would `<QuerySet>.delete()` call the overridden `delete` method and soft delete or does it hard delete?

**Comment by rithviknishad** [comment]
@yaswanthsaivendra also could you prefix the issue numbers with "Fixes" or other linking keywords?

**Comment by yaswanthsaivendra** [comment]
> You are performing `<QuerySet>.delete()`. However, we've overridden the `<Instance>.delete()` to soft delete only. Would `<QuerySet>.delete()` call the overridden `delete` method and soft delete or does it hard delete?

🤦😅 hard delete, made changes to soft delete

**Comment by yaswanthsaivendra** [comment]
> @yaswanthsaivendra also could you prefix the issue numbers with "Fixes" or other linking keywords?

My bad, I did all changes in single commit 😮‍💨. Referenced the changes in each task.

**Comment by vigneshhari** [comment]
@sainak Can you review?

**Pull request closed without merging**
