### PR TITLE
fix: adds tests for auth and token endpoints

### LINKED ISSUE #1376: Adds test for `authentication` and `token verification/refresh` endpoints

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- [x] Adds test for auth and token verification

## Associated Issue

- Fixes #1376

## Merge Checklist

- [x] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Comment by sainak** [comment]
@cp-Coder Split up the test cases, this will help better in tracking the issue and speed up tests

**Review by sainak — CHANGES_REQUESTED** [review]
Test cases need to be separated

**Review by vigneshhari — APPROVED** [review]

**Comment by vigneshhari** [comment]
@sainak can you separate it out, we can merge it right away.

**Comment by sainak** [comment]
> @sainak can you separate it out, we can merge it right away.

on it

**Review by sainak — APPROVED** [review]

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
