### PR TITLE
add pre-commit-hooks - black, isort, django-migrations-check

### PR DESCRIPTION
**Pull request by anroopak**
Though this looks like a huge diff, the major diff is only in the pre-commit config files.

View only these files - 
.pre-commit-config.yaml
setup.cfg

Rest of the files have been changed due to these pre-commit hook changes

Related Issue: https://github.com/coronasafe/care/issues/71

### CODE REVIEW

**Comment by tucosaurus** [comment]
The only issue I see with this is that it overwrites the git history for quite a number of files. A `git blame` would not be that helpful to get the context for a line of code. If the maintainers are fine with that, this is good to merge. @biswaz @vigneshhari

**Comment by anroopak** [comment]
It does not overwrite, it appends to the git history. Git blame and still find the previous editors (I assume). And this is only one-time, after every developer starts using the hooks, editors would be the particular dev only.

**Comment by vigneshhari** [comment]
@biswaz review and merge

**Comment by biswaz** [comment]
@anroopak could you document usage, such as manually triggering the hooks etc (if possible) in the README

**Comment by biswaz** [comment]
Also add precommit package to requirements file (assuming you are using that). Any other helpful commands from https://pre-commit.com/ wil help

**Comment by anroopak** [comment]
@biswaz added documentation. `pre-commit` was already part of the initial requirements.

**Pull request merged**
