### PR TITLE
Removed current health field

### LINKED ISSUE #880: Remove current health as a field from daily rounds api
The current health field has been removed from the daily round form so remove the unused field from API in this PR https://github.com/coronasafe/care_fe/issues/2761

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #880
- [x] Removed `current health` from API, migration, model

### CODE REVIEW

**Review by sainAk — CHANGES_REQUESTED** [review]
Create new migrations instead of editing previous ones.

**Comment by cp-Coder** [comment]
@sainAk Okay I will make new migration

**Comment by cp-Coder** [comment]
@sainAk I have added new migrations

**Comment by cp-Coder** [comment]
Also this field is also present in the template. So do I have to delete from template too?

**Comment by sainAk** [comment]
> Also this field is also present in the template. So do I have to delete from template too?

we are not using template views anymore and it is planned to be removed so its fine to leave it as it is.

**Review by sainAk — APPROVED** [review]

**Comment by cp-Coder** [comment]
> > Also this field is also present in the template. So do I have to delete from template too?
> 
> we are not using template views anymore and it is planned to be removed so its fine to leave it as it is.

Okay

**Review by vigneshhari — APPROVED** [review]

**Pull request closed without merging**
