### PR TITLE
Medicines: replace in-memory search with pg full text search with GIN index

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Removed in-memory table `MedibaseMedicinesTable` and support for in-memory search.
- Adds GIN Index on the Medicines table (+ migration to install the Postgres extension)
- Annotates and orders with search rank (priority: `generic`, `name`, `company`, `cims_class`, `contents`)
- Updated API endpoint and views to reflect the changes and support for pagination.

### Before: with the in-memory table (93ms ~ 128ms)

image

### After: Search on Postgres with GIN Index and order by `SearchRank` (122ms ~ 170ms)

(Postgres is not on the same machine; on a Linux machine on the same local network)

image

### Index Size (~64 MB)

image

## Merge Checklist

- [x] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Comment by rithviknishad** [comment]
will update tests

**Review by sainak — APPROVED** [review]

**Review by sainak — APPROVED** [review]

**Comment by sainak** [comment]
Migrations tested on latest staging snapshot

**Comment by rithviknishad** [comment]
@sainak external_id was hidden too?

**Comment by sainak** [comment]
Yeah we are using the id field for it right

**Comment by rithviknishad** [comment]
oh my bad; got confused

**Comment by nihal467** [comment]
image

I tested in tunnel provided by @rithviknishad's and added multiple medicines to a patients but partial search is not giving expected results

**Comment by rithviknishad** [comment]
Alternate approach used. Completed via #1443

**Pull request closed without merging**
